name: fillogo
description: A social media application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.9.8+9

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^5.0.0
  url_launcher: ^6.0.6
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  connectivity_plus: ^2.3.5
  http: ^0.13.4
  get: ^4.6.5
  flutter_svg: ^1.1.1+1
  blurrycontainer: ^1.0.2 
  permission_handler: ^10.2.0
  story_view: ^0.16.0
  flutter_switch: ^0.3.2
  google_maps_flutter: ^2.2.8
  location: ^5.0.3
  flutter_polyline_points: ^1.0.0
  pinput: ^2.2.12
  geolocator: ^9.0.1
  geocoding: ^2.0.5
  r_dotted_line_border: ^0.1.1
  intl: ^0.19.0
  grouped_list:
  google_directions_api: ^0.9.1
  crypto: ^3.0.2
  dart_des: ^1.0.2
  flutter_background_service: ^2.4.6
  flutter_screenutil: ^5.6.0
  google_maps_routes: ^1.1.2
  masked_text: ^1.1.2
  share_plus: ^7.2.2
  modal_bottom_sheet: ^2.1.2
  flutter_google_places_hoc081098: ^1.2.0
  google_api_headers: ^1.5.0+1
  google_maps_webservice: ^0.0.20-nullsafety.5
  geocoder2: ^1.4.0
  google_mobile_ads: ^3.0.0
  google_places_flutter: ^2.0.8
  lottie: ^2.3.1
  animated_text_kit: ^4.2.2
  mask_text_input_formatter: ^2.4.0
  image_picker: ^0.8.7+1
  image_cropper: ^3.0.2
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12
  
  flutter_localizations:
    sdk: flutter
  socket_io_client: ^2.0.1
  logger: ^1.3.0
  onesignal_flutter: ^5.1.3
  flutter_local_notifications: ^17.2.1
  file_picker: ^6.0.0
  timeago: ^3.3.0
  video_compress: ^3.1.2
  infinite_scroll_pagination: ^4.0.0
  image_to_byte: ^1.0.0
  flutter_compass: ^0.8.0
  multipart: ^0.1.2
  dio: ^5.4.3+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.4

flutter_native_splash:
  background_image: assets/images/8.png
  image: assets/logo/logo-5.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/emotions/
    - assets/logo/
    - assets/fonts/
    - assets/json/user/
    - assets/json/

  fonts:
    - family: Sfblack
      fonts:
        - asset: assets/fonts/sf-ui-black.otf

    - family: Sfbold
      fonts:
        - asset: assets/fonts/sf-ui-bold.otf

    - family: Sfheavy
      fonts:
        - asset: assets/fonts/sf-ui-heavy.otf

    - family: Sflight
      fonts:
        - asset: assets/fonts/sf-ui-light.otf

    - family: Sfmedium
      fonts:
        - asset: assets/fonts/sf-ui-medium.otf

    - family: Sfsemibold
      fonts:
        - asset: assets/fonts/sf-ui-semibold.otf

    - family: Sfthin
      fonts:
        - asset: assets/fonts/sf-ui-thin.otf

    - family: Sfultralight
      fonts:
        - asset: assets/fonts/sf-ui-ultralight.otf
